### ISSUE TITLE
Cloudmos SDL builder is completely and utterly broken on Brave, Debian.

### ISSUE THREAD

**Issue by bitcoinmeetups** [akash-network/cloudmos#26]
Hi,

I'm Mr. Tetroid, a very friendly guy.

Cloudmos SDL builder is completely and utterly broken in Brave browser running on Debian 11.

1. If you try to save, usually it just says "error fetching template". Then it DELETES all the SDL template info so you have to start from scratch.
2. If you leave the SDL builder page and come back, nothing has been saved, even if you have occasionally been able to save.

This is nuts. It takes a little while to put an SDL file together and then it just gets wiped most of the time. No way to preview before wiping either. Come on make SDL building a nice experience. As of now it is extremely buggy and also the saving capability does not seem to be persistent anyway. Worst kind of SDL builder.

**Comment by baktun14** [comment]
@bitcoinmeetups I've implemented persistence for the SDL Builder and added a preview to view the yaml. We'll release soon after merging the PR, let us know if it improves your experience!
