### ISSUE TITLE
Improve UX for when a bid selection is ignored 

### ISSUE THREAD

**Issue by anilmurty** [akash-network/cloudmos#29]
selecting a provider and then canceling the transaction (to choose another provider) requires a refresh of the page for the "accept bid" button to become active again. It may be better to cancel the keplr transaction if the bid selection popup is closed, so that the bid selection UI is active again (and the user can select a different provider)

**Comment by Redm4x** [comment]
Looks like it is not possible to close the Keplr popup from code when the "Pending Tx" modal is closed. We instead decided to prevent the closing of the "Pending tx" by removing the "X" button and changing the text to force the user to either Approve or Reject/Close the tx in keplr before continuing (#36). That prevents some issue that could happen if a keplr modal is kept open and is later approved when the UI is no longer expecting it to complete.
