### ISSUE TITLE
Improve SDL Builder UX

### ISSUE THREAD

**Issue by anilmurty** [akash-network/cloudmos#34]
The SDL builder UX can use a couple of improvements:
- [x] 1. When users come into cloudmos the first time (or really any time) the natural inclination is to click on "Deploy" and get going. The challenge is that this workflow requires that the user either already have an SDL or be able to create one on the fly or use a pre-defined template. It doesn't account for the user who just wants to deploy a custom SDL but doesn't know how to write the file. While this is supported in the SDL builder, the user needs to first go and create the SDL there and then copy it into the SDL editor in the deploy workflow. It would be great to just have the SDL builder UI show up in the deploy workflow. Ideally, even for the preset templates, it will be great if the first thing the user sees when they click them is the SDL builder (pre-configured to match the templated SDL) that they can change if they want. Optionally the more advanced users should always have the option to edit SDL. This is much like the workflow in Console.
- [x] 2. A user has reported issues with using the SDL editor that may be specific to Brave browsers: https://github.com/akash-network/cloudmos/issues/26

**Comment by baktun14** [comment]
I added the SDL Builder inside the deployment wizard and also addressed the issues mentionned in #26. 

Ref #35 

![image](https://github.com/akash-network/cloudmos/assets/15185355/b776ab0a-eac6-4533-b49f-56f05a4ffaad)

**Comment by anilmurty** [comment]
awesome!
